
export const strings = {
  en: {
    Welcome: 'Welcome',
    Acces: 'Acces',
    Enter:'Enter',
    User_Panel: 'User Panel',
    Security: 'Security',
    Logout: 'Logout',
    Sign_in: 'Sign In',
    Login: 'Login',
    Home: 'Home',
    Page: 'Page',
    of: 'of',
    Detail: 'Detail',
    Screenshot: 'screenshot',
    Extra: 'Extra',
    Minimum_requirements: "Minimum Requirements",
    Genres: "Genres",
    Plataformas: "Platforms",
    Capture:'Capture',
    Item_added:'Item Added',
    Shopping_Car: 'Shopping Car',
    Items: 'Items',
    Number: 'Number',
    Price: 'Price',
    Checkout : 'Checkout',
    MsgUserNoRegister: 'Unregistered User login to your account',
    Search: 'Search',
    
  },
  es: {
    Welcome: 'Bienvenido',
    Acces: 'Acceder',
    Enter:'Ingresar',
    User_Panel: 'Panel de Usuario',
    Security: 'Securidad',
    Logout: 'Salir',
    Sign_in: 'Registrate',
    Login: 'Iniciar Sesión',
    Home: 'Inicio',
    Page: 'Pagina',
    of: 'de',
    Detail: 'Detalle',
    Screenshot: 'Captura de Pantalla',
    Extra: 'Extra',
    Minimum_requirements: "Requirimientos Minimos ",
    Genres: "Generos",
    Plataformas: "Plataformas",
    Capture:'Capturas',
    Item_added:'Artículo añadido',
    Shopping_Car: 'Carrito de Compras',
    Items: 'Articulos',
    Number: 'Número',
    Price: 'Precio',
    Checkout : 'Pago',
    MsgUserNoRegister: 'Usuario no registrado acceda a su cuenta',
    Search: 'Buscar',
  }
};



