
export const strings = {
  en: {
    Welcome: 'Welcome',
    Acces: 'Acces',
    Enter:'Enter',
    User_Panel: 'User Panel',
    Security: 'Security',
    Logout: 'Logout',
    Sign_in: 'Sign In',
    Login: 'Login',
    Home: 'Home',
    Page: 'Page',
    of: 'of',
    Detail: 'Detail',
    Screenshot: 'Screenshot',
    Extra: 'Extra',
    Minimum_requirements: "Minimum Requirements",
    Genres: "Genres",
    Plataformas: "Platforms",
    Capture:'Capture',
    Item_added:'Item Added',
    Shopping_Car: 'Shopping Car',
    Items: 'Items',
    Number: 'Number',
    Price: 'Price',
    Checkout : 'Checkout',
    MsgUserNoRegister: 'Unregistered User login to your account',
    Search: 'Search',
    Information: 'Information',
    Ranking: 'Ranking',
    Release: 'Release Date',
    DarkMode: 'Dark Mode',
    Languaje:  'Change Language',
    Landing: 'Landing',
    MyVideogames:'MyVideo Games',
    Communications: 'Communications',
    MyPosts: 'My Posts',
    youtCart: 'Your Cart',
    clCart:'Clear Cart',
    chkOut:'CheckOut',
    emptycar: 'Your cart is empty',
  },
  es: {
    Welcome: 'Bienvenido',
    Acces: 'Acceder',
    Enter:'Ingresar',
    User_Panel: 'Panel de Usuario',
    Security: 'Securidad',
    Logout: 'Salir',
    Sign_in: 'Registrate',
    Login: 'Iniciar Sesión',
    Home: 'Inicio',
    Page: 'Pagina',
    of: 'de',
    Detail: 'Detalle',
    Screenshot: 'Captura de Pantalla',
    Extra: 'Extra',
    Minimum_requirements: "Requerimientos Minimos ",
    Genres: "Generos",
    Plataformas: "Plataformas",
    Capture:'Captura',
    Item_added:'Artículo añadido',
    Shopping_Car: 'Carrito de Compras',
    Items: 'Articulos',
    Number: 'Número',
    Price: 'Precio',
    Checkout : 'Pago',
    MsgUserNoRegister: 'Usuario no registrado acceda a su cuenta',
    Search: 'Buscar',
    Information: 'Informacion',
    Ranking: 'Clasificación',
    Release: 'Fecha de Lanzamiento',
    DarkMode: 'Modo Oscuro',
    Languaje:  'Cambiar Lenguaje',
    Landing: 'Aterrizaje',
    MyVideogames:'Mis Video Juegos',
    Communications: 'Comunicaciones',
    MyPosts: 'Mis Mensajes',
    youtCart: 'Su cesta',
    clCart:'Borrar cesta',
    chkOut:'Pagar',
    emptycar: 'Su cesta está vacía',
  }
};



