
export const strings = {
  en: {
    Welcome: 'Welcome',
    Acces: 'Acces',
    Enter:'Enter',
    Dashboard: 'Dashboard',
    Security: 'Security',
    Logout: 'Logout',
    Register: 'Register',
    Login: 'Login',
    Home: 'Home',
    Page: 'Page',
    of: 'of',
    Detail: 'Detail',
    Screenshot: 'Screenshot',
    Extra: 'Extra',
    Minimum_requirements: "Minimum Requirements",
    Genres: "Genres",
    Plataformas: "Platforms",
    Capture:'Capture',
    Item_added:'Item Added',
    Shopping_Car: 'Shopping Car',
    Items: 'Items',
    Number: 'Number',
    Price: 'Price',
    Checkout : 'Checkout',
    MsgUserNoRegister: 'Unregistered User login to your account',
    Search: 'Search',
    Information: 'Information',
    Ranking: 'Ranking',
    Release: 'Release Date',
    DarkMode: 'Dark Mode',
    Languaje:  'Change Language',
    Landing: 'Landing',
    MyVideogames:'MyVideo Games',
    Communications: 'Communications',
    MyPosts: 'My Posts',
    youtCart: 'Your Cart',
    clCart:'Clear Cart',
    chkOut:'CheckOut',
    emptycar: 'Your cart is empty',
    MsgAlertTitle:'Are you sure you want to clear the cart?' ,
    optCancel: 'Cancel',
    remove:'Remove',
    MsgAlertAmountMax:'Sorry, the maximum number of purchases per title is 3.',
    MsgAlertItemAmountAdd: 'One unit has been added to the current item',
    MSGAlertItemAdd: 'Item has been added',
    addItemCar: 'Add to cart',
    Sign_inWith: 'Sign in with',
    or: 'Or',
    userName:'User Name',
    CartValidate:'Attention, you must log in to proceed with the purchase.',
    Pasarella: 'Payment Gateway',
  },
  es: {
    Welcome: 'Bienvenido',
    Acces: 'Acceder',
    Enter:'Ingresar',
    Dashboard: 'Panel de Usuario',
    Security: 'Securidad',
    Logout: 'Cerrar la sesión',
    Register: 'Registrate',
    Login: 'Iniciar Sesión',
    Home: 'Inicio',
    Page: 'Pagina',
    of: 'de',
    Detail: 'Detalle',
    Screenshot: 'Captura de Pantalla',
    Extra: 'Extra',
    Minimum_requirements: "Requerimientos Minimos ",
    Genres: "Generos",
    Plataformas: "Plataformas",
    Capture:'Captura',
    Item_added:'Artículo añadido',
    Shopping_Car: 'Carrito de Compras',
    Items: 'Articulos',
    Number: 'Número',
    Price: 'Precio',
    Checkout : 'Pago',
    MsgUserNoRegister: 'Usuario no registrado acceder a su cuenta',
    Search: 'Buscar',
    Information: 'Informacion',
    Ranking: 'Clasificación',
    Release: 'Fecha de Lanzamiento',
    DarkMode: 'Modo Oscuro',
    Languaje:  'Cambiar Lenguaje',
    Landing: 'Aterrizaje',
    MyVideogames:'Mis Video Juegos',
    Communications: 'Comunicaciones',
    MyPosts: 'Mis Mensajes',
    youtCart: 'Tu cesta',
    clCart:'Borrar cesta',
    chkOut:'Pagar',
    emptycar: 'Tu cesta está vacía',
    MsgAlertTitle:'¿Estás seguro de que quieres vaciar el carrito?' ,
    optCancel: 'Cancelar',
    remove:'Eliminar',
    MsgAlertAmountMax:'Lo Sentimos el numero maximo de compras por titulo es 3.',
    MsgAlertItemAmountAdd: 'Se adiciono una unidad al item actual',
    MSGAlertItemAdd: 'Ítem ha sido agregado',
    addItemCar: 'Añadir a la Cesta',
    Sign_inWith: 'Registrate con',    
    or: 'O',
    userName:'Nombre de Usuario',
    CartValidate:'Atencion, debe iniciar sesión para proceder con compra.',
    Pasarella: 'Pasarela de Pago',
  }
};



